sudo: required
services:
  - docker

before_install:
  - docker build -t dmytrokyiashko/docker-react -f Dockerfile.dev .

script:
  - docker run dmytrokyiahsko/docker-react npm run test -- --coverage
