sudo: required
services:
  - docker

before_install:
  - docker build -t dmytrokyiashko/docker-react -f Dockerfile.dev .

script:
  - docker run dmytrokyiashko/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-310581963285"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACSCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"